### ISSUE TITLE
F4 brings up menu, but upon click nothing works.

### ISSUE THREAD

**Issue by Xeddius** [bendgk/basewars#1]
When bringing up the basewars menu, I am able to click on all of the options, however nothing is displayed on the interface. It's just blank aside from the leftside menu buttons.

**Comment by bendgk** [comment]
Honestly, this was a project a friend and I were working on over the summer.  I only got as far as implementing the menu and even that is still very beta and not completely working.  I hope one day I can return to this project and recreate the original basewars but until then this project is postponed.
